[project]
profile = "rust"

[rust]
image = "rust:latest"
setup = "rustup component add --toolchain stable-x86_64-unknown-linux-gnu clippy rustfmt"

[rust.fmt]
desc = "Apply format."
cmd = "cargo fmt"

[rust.clippy]
desc = "Apply clippy."
cmd = "cargo clippy --fix --allow-dirty"

[rust.build]
desc = "Compile in debug mode."
cmd = "cargo build"

[rust.release]
desc = "Compile in release mode."
cmd = "cargo build --release"

[rust.exec]
desc = "Run app."
cmd = "cargo run"
interactive = true
hidden = true

[rust.run]
desc = "Run app"
pipeline = ["build", "exec"]

[rust.shell]
desc = "Run shell."
cmd = "bash"
interactive = true

[claude]
image = "rust:latest"
setup = """
(type -p wget >/dev/null || (apt-get update && apt-get install wget -y)) \
    && mkdir -p -m 755 /etc/apt/keyrings \
    && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
    && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
    && mkdir -p -m 755 /etc/apt/sources.list.d \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && apt-get update \
    && apt-get install gh -y \
    && rustup component add --toolchain stable-x86_64-unknown-linux-gnu clippy rustfmt \
    && curl -fsSL https://claude.ai/install.sh | bash
"""

[claude.run]
desc = "Run claude."
cmd = "~/.local/bin/claude"
interactive = true

[claude.shell]
desc = "Run claude."
cmd = "bash"
interactive = true
